### ISSUE TITLE
Create Authors yaml key, list and ui

### ISSUE THREAD

**Issue by thanpolas** [closureplease/closureplease.com#15]
create a key for yaml front matter on posts `author` which will accept a value from a separate yaml file that will contain the author's data (name, email, website, twitter ...)

Then present the data to the post.

yaml front matter on post:

``` yaml
----
-author: rhys
----
```

yaml file with authors:

``` yaml
authors:
  rhys:
    name : "Rhys Brett-Bowen"
    email : ""
    github : rhysbrettbowen
    twitter : rhysbb
```
